### ISSUE TITLE
Test on SHTC1 and maybe SHTW2

### ISSUE THREAD

**Issue by dbrgn** [dbrgn/shtcx-rs#11]
@rnestler maybe you could do this?

To build the examples:

    ./build-rpi.sh

Then copy `target/arm-unknown-linux-musleabihf/release/examples/linux-shtc1` to the Raspberry Pi and run it.

If this works, you could update the "Tested with the following sensors" section in `README.md` and in the docs in `src/lib.rs`.

**Comment by dbrgn** [comment]
Once this is tested, I can release version 0.2.0.

**Comment by rnestler** [comment]
I tested with an SHTW2
```
Starting SHTC1 tests.

Device identifier: 0x7
Raw ID register:   0b11000111

Measurements:
- 24.70 °C | 33.84 %RH
- 24.76 °C | 33.90 %RH
- 24.75 °C | 33.85 %RH
```
Btw. The `-` in front of the temperature is very confusing :D

**Comment by rnestler** [comment]
And with the SHTC1
```
Starting SHTC1 tests.

Device identifier: 0x7
Raw ID register:   0b10000111

Measurements:
- 25.16 °C | 29.24 %RH
- 25.18 °C | 29.34 %RH
- 25.14 °C | 29.39 %RH
```

**Comment by dbrgn** [comment]
I also re-tested the current version on both SHTC1 and SHTC3. Works without any problems.
