### ISSUE TITLE
Support for embedded-hal 1.0

### ISSUE THREAD

**Issue by ShakenCodes** [dbrgn/shtcx-rs#31]
Breaking changes in embedded-hal 1.0.0-rc.1 are incompatible with this driver.
I have a working version at: https://github.com/Radiator-Labs/shtcx-rs, and will submit a PR when the complete build is operational. The driver operates correctly, which I am testomg on an STM32WL55 application.

I am not able to submit the PR at this time, as one of the dev-dependencies, embedded-hal-mock, is not compatible with embedded-hal 1.0.0-rc.1. There is a PR awaiting incorporation, which is tracked by: https://github.com/dbrgn/embedded-hal-mock/pull/86 (Which I now realize is also by you. Thank you for all the goodness!)
linux-embedded-hal is up to the new standard, as of: https://github.com/rust-embedded/linux-embedded-hal/pull/96

**Comment by dbrgn** [comment]
Thanks! I reviewed the embedded-hal-mock PR, once it's merged I think I can push a new release 🙂

**Comment by dbrgn** [comment]
An updated embedded-hal-mock is now released (0.10.0-rc.1)!

**Comment by dbrgn** [comment]
By now the embedded-hal 1.0 stable was released, and embedded-hal-mock also has a release that supports it (0.10.0). It was already updated in #33.

I hope I find time in the coming 1-2 weeks to update the driver. Alternatively, PRs are welcome. (But if you start working on it, please comment here first, so that there is no duplicated effort.)

**Comment by ShakenCodes** [comment]
I may have time in the next couple of days. I think a contractor that has been helping my team may have already fixed this on a branch.

**Comment by ShakenCodes** [comment]
Pull request is submitted, but the GitHub Actions do not seem to be starting.

**Comment by ShakenCodes** [comment]
I am having problems getting this all to work, especially the library's tests. @dbrgn Would you be open to a virtual pairing session to get this over the finish line? (I am in the Pacific time zone and could be available form reasonably early in the morning and well into the evening. My availability starts in the week of March 18, but I thought it would make sense to start planning now.

**Comment by dbrgn** [comment]
@ShakenCodes virtual pairing is a bit difficult at the moment, I have quite a full schedule over the next few weeks. what's the main issue you're stuck with?

you could also push your current state, and I could try to pick up from that.
