### ISSUE TITLE
Feature Request: Support for SHT4x series

### ISSUE THREAD

**Issue by dylif** [dbrgn/shtcx-rs#42]
As the title says: Would it be possible add support for the SHT4x series of chips?

If it's too much hassle or simply not desired, no hard feelings. Just thought I'd ask.

**Comment by rnestler** [comment]
From the name of the crate SHTCX it doesn't make sense to support other sensors than that family (https://sensirion.com/search/products?q=SHTCx).

The SHTWx sensors are supported as well since they are the same chip in a different package.

**Comment by rnestler** [comment]
On crates.io I found https://crates.io/crates/sht4x and https://crates.io/crates/sensor-temp-humidity-sht40 which seem to support the SHT4x series.

**Comment by dylif** [comment]
Thank you for finding those, really appreciate it! I'll close this issue now.
